demo/config/routes.rb
Demo::Application.routes.draw do
  resources :newsboards

end

demo/app/models/newsboard.rb
class Newsboard < ActiveRecord::Base
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/newsboards_controller.rb
class NewsboardsController < ApplicationController
  # GET /newsboards
  # GET /newsboards.json
  def index
    @newsboards = Newsboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsboards }
    end
  end

  # GET /newsboards/1
  # GET /newsboards/1.json
  def show
    @newsboard = Newsboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsboard }
    end
  end

  # GET /newsboards/new
  # GET /newsboards/new.json
  def new
    @newsboard = Newsboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsboard }
    end
  end

  # GET /newsboards/1/edit
  def edit
    @newsboard = Newsboard.find(params[:id])
  end

  # POST /newsboards
  # POST /newsboards.json
  def create
    @newsboard = Newsboard.new(params[:newsboard])

    respond_to do |format|
      if @newsboard.save
        format.html { redirect_to @newsboard, notice: 'Newsboard was successfully created.' }
        format.json { render json: @newsboard, status: :created, location: @newsboard }
      else
        format.html { render action: "new" }
        format.json { render json: @newsboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsboards/1
  # PUT /newsboards/1.json
  def update
    @newsboard = Newsboard.find(params[:id])

    respond_to do |format|
      if @newsboard.update_attributes(params[:newsboard])
        format.html { redirect_to @newsboard, notice: 'Newsboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsboards/1
  # DELETE /newsboards/1.json
  def destroy
    @newsboard = Newsboard.find(params[:id])
    @newsboard.destroy

    respond_to do |format|
      format.html { redirect_to newsboards_url }
      format.json { head :no_content }
    end
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/newsboards_helper.rb
module NewsboardsHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/newsboards/_form.html.erb
<%= form_for(@newsboard) do |f| %>
  <% if @newsboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsboard.errors.count, "error") %> prohibited this newsboard from being saved:</h2>

      <ul>
      <% @newsboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="rss">
  <script type="text/javascript" src="http://app.feed.informer.com/digest3/XR5SQY9NL5.js"></script>
<noscript><a href="http://app.feed.informer.com/digest3/XR5SQY9NL5.html">Click for &quot;Your New Digest 1&quot;.</a>
Powered by <a href="http://feed.informer.com/">RSS Feed Informer</a></noscript>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/newsboards/edit.html.erb
<h1>Editing newsboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsboard %> |
<%= link_to 'Back', newsboards_path %>

demo/app/views/newsboards/index.html.erb
<h1>Listing newsboards</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newsboards.each do |newsboard| %>
  <tr>
    <td><%= link_to 'Show', newsboard %></td>
    <td><%= link_to 'Edit', edit_newsboard_path(newsboard) %></td>
    <td><%= link_to 'Destroy', newsboard, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newsboard', new_newsboard_path %>

demo/app/views/newsboards/new.html.erb
<h1>New newsboard</h1>

<%= render 'form' %>

<%= link_to 'Back', newsboards_path %>

demo/app/views/newsboards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_newsboard_path(@newsboard) %> |
<%= link_to 'Back', newsboards_path %>